### PR TITLE
Fix "bugs" with join

### PR DESCRIPTION
**Pull request by C0DK**
made it possible join with @ and # prepended as well. Also made it possible if it's written in a singular string ie `@team#channel` - also doesn't bug out if you do `/j @person ` (with a space at the end)

### CODE REVIEW

**Comment by C0DK** [comment]
Lacks the `@team#channel` feature - i'm working on it! :)

**Review by Rudi9719 — CHANGES_REQUESTED** [review]
Please only request to dev, that way it can be tested with all other changes before going to master on Wednesday. Also, `go fmt` is a good command to run before pushing :)

**Comment by Rudi9719** [comment]
I might be able to manually pull your branch into dev

**Comment by C0DK** [comment]
There we go :) now it has the correct base

**Comment by C0DK** [comment]
and i'm formatting it now.

**Comment by C0DK** [comment]
I think i ran format on this (i didn't on the color thing - my bad :) ) and it was foramtted correct already.

**Pull request merged**
