### PR TITLE
Make 'dev' flag usable

### PR DESCRIPTION
**Pull request by ricardobalk**
With this commit it becomes possible to set the dev flag to true, which will allow you to send and receive chat messages in dev channels only. You can use this to test kbtui without being disruptive.

### CODE REVIEW

**Comment by ricardobalk** [comment]
Wut, why did `.string()` go away o.o

**Review by Rudi9719 — COMMENTED** [review]
Is there anywhere in current/other code to change the dev flag? I was working on this a while ago (so there might) but I thought I removed/scrapped it because of issues it was having with chat in Dev channels.

**Comment by ricardobalk** [comment]
Well, the problem I got when I used the dev flag (boolean set to true) was that incoming non-dev messages (type "chat") showed up as well. But with this commit both incoming and outgoing messages are either "dev" or "chat", based on the global boolean value set on top of the code.

Maybe you should checkout this specific commit and test it :)

**Comment by ricardobalk** [comment]
It crashes when you try to join a team without specifying the chat channel (e.g. `/j kbtui`), but it works when you join and specify the chat channel (e.g. `/j kbtui general`).

image

But `/j kbtui` just gives
```
goroutine 54 [running]:
main.populateChat()
	/home/undisclosed/Local/Git/GitHub/ellipticcurv3/kbtui/main.go:400 +0x6a2
created by main.cmdJoin
	/home/undisclosed/Local/Git/GitHub/ellipticcurv3/kbtui/cmdJoin.go:49 +0x577
```

Is that what you meant @Rudi9719 ?

**Comment by Rudi9719** [comment]
No - that was an unrelated issue. If you pull the latest from dev (branch) you should get a fix for it. I was having issues before where when reading dev channels, other messages would show- and the messages sent to the dev channels weren't working properly. I'll check it out and see if you fixed it :D

**Comment by Rudi9719** [comment]
I tried to pull this and test it, seems like you're having a similar issue to what I was having. When enabling the dev flag (and cleaning / reloading the convo) dev messages appear. However you have to reload the convo every time you send (or receive?) a message for some reason. I made a CMD Dev to see how it worked, I also tried adding lines to clear the convo and auto-pull messages but it got irate at that

https://github.com/Rudi9719/kbtui/tree/ellipticcurv3/kbtui

**Comment by ricardobalk** [comment]
I managed to get this working, however, you can't simply "switch" to "dev" mode. To receive dev messages, Keybase (`keybase chat api-listen`) needs to be reinitialized with the new flag. In kbtui, this happens in `func updateChatWindow()`, as shown below.

```
// Update/Populate views automatically
func updateChatWindow() {

	runOpts := keybase.RunOptions{
		Dev: dev,
	}
	k.Run(func(api keybase.ChatAPI) {
		handleMessage(api)
	},
		runOpts)
}
```

Problem I'm facing now is that there's no way to kill the previous process, so I'm spawning another one. When you switch back to topicType `chat` simply by using `/dev`, you will have duplicate incoming messages ... because you have 3 individual `keybase chat api-listen` processes spawned.

So we either have to make kbtui always listen for incoming dev messages and filter them or somehow kill the previously spawned process before spawning a new one.

First option would be the best one, from my point of view.

**Pull request closed without merging**
